spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# local 환경
---
spring:
  profiles: local
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jpatest?useUnicode=true&characterEncoding=utf8
    username: JPA
    password: ys0109bf
  jpa:
    hibernate:
      #ddl-auto: create
      ddl-auto: none
    show-sql: true
    database: mysql

logging:
  level:
    org:
      hibernate: info
